"""Generate SYNTHETIC observations from a night plan, for exercising the ledger.

    python tools/mock_observe.py data/nights/night_2026-09-12_visnjan.json
    python tools/mock_observe.py data/nights/night_2026-09-12_visnjan.json \
           --completion 0.55 --seeing 3.1 --fail-rate 0.05 --seed 7

Writes a frame list to data/mock/frames_<date>_<telescope>.csv in exactly the
format tools/reconcile.py consumes, then folds it into data/coverage.json the
same way real frames would be — so the mock path exercises the real code.

EVERYTHING IT PRODUCES IS FAKE and is marked as such in three places: the night
record carries "mock": true, its note begins with SYNTHETIC, and the frame CSV
carries a MOCK header comment plus a mock=1 column on every row. The web page
shows a magenta banner whenever any mock night is loaded, and lets you exclude
mock data from coverage with one click. Delete data/mock/ and the mock nights
from coverage.json to get back to a clean ledger.

Not simulated: pixels. This produces frame *metadata* only — enough to drive the
planner and the coverage map, not enough to pretend it is imagery.
"""
import argparse, csv, json, random
from pathlib import Path
import numpy as np
from grid import build_grid, TELESCOPES, DEFAULT, ang_sep

ROOT = Path(__file__).resolve().parent.parent
MOCK_NOTE = "SYNTHETIC — generated by tools/mock_observe.py, not real observations"


def simulate(plan, completion, seeing, fail_rate, rng):
    """Walk the plan in order, dropping the tail (overhead) and scattered frames."""
    scope = plan.get("telescope", DEFAULT)
    spec = TELESCOPES[scope]
    by_id = {t["id"]: t for t in build_grid(scope)}
    planned = [i for i in plan["planned"] if i in by_id]

    # the night stops partway through: real overhead eats the tail
    n_done = int(round(len(planned) * completion))
    attempted = planned[:n_done]

    frames = []
    for tid in attempted:
        t = by_id[tid]
        for filt in spec["filters"]:
            if rng.random() < fail_rate:
                continue                      # dropped frame: cloud, failed solve, guide loss
            # pointing scatter, arcsec-level, as a real centring would leave
            dra = rng.gauss(0, 3.0) / 3600 / max(0.05, np.cos(np.radians(t["dec"])))
            ddec = rng.gauss(0, 3.0) / 3600
            frames.append({
                "ra_deg": round(t["ra"] + dra, 6),
                "dec_deg": round(t["dec"] + ddec, 6),
                "filter": filt,
                "fwhm_arcsec": round(max(0.6, rng.gauss(seeing, seeing * 0.18)), 2),
                "exptime_s": plan.get("params", {}).get("expSec", spec["exposure_s"]),
                "tile_hint": tid,
                "mock": 1,
            })
    return frames, attempted


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("plan")
    ap.add_argument("--completion", type=float, default=0.6,
                    help="fraction of the plan actually attempted (default 0.6)")
    ap.add_argument("--seeing", type=float, default=2.5, help="median FWHM arcsec")
    ap.add_argument("--fail-rate", type=float, default=0.03, help="per-frame dropout")
    ap.add_argument("--seed", type=int, default=None)
    ap.add_argument("--tol", type=float, default=0.4)
    a = ap.parse_args()

    rng = random.Random(a.seed)
    plan = json.loads(Path(a.plan).read_text())
    date, scope = plan["date"], plan.get("telescope", DEFAULT)

    frames, attempted = simulate(plan, a.completion, a.seeing, a.fail_rate, rng)
    if not frames:
        raise SystemExit("simulated nothing — check --completion")

    mock_dir = ROOT / "data" / "mock"
    mock_dir.mkdir(parents=True, exist_ok=True)
    csv_path = mock_dir / f"frames_{date}_{scope}.csv"
    with open(csv_path, "w", newline="") as f:
        f.write(f"# {MOCK_NOTE}\n# plan={Path(a.plan).name} seed={a.seed} "
                f"completion={a.completion} seeing={a.seeing} fail_rate={a.fail_rate}\n")
        w = csv.DictWriter(f, fieldnames=list(frames[0].keys()))
        w.writeheader(); w.writerows(frames)

    # --- fold into coverage exactly as reconcile.py would ---
    tiles = build_grid(scope)
    tra = np.array([t["ra"] for t in tiles]); tdec = np.array([t["dec"] for t in tiles])
    hit, unmatched = {}, 0
    for fr in frames:
        d = ang_sep(tra, tdec, fr["ra_deg"], fr["dec_deg"])
        i = int(np.argmin(d))
        if d[i] <= a.tol:
            hit.setdefault(tiles[i]["id"], []).append(fr["filter"])
        else:
            unmatched += 1

    observed = [{"id": k, "filters": sorted(v)} for k, v in sorted(hit.items())]
    need = set(TELESCOPES[scope]["filters"])
    complete = sum(1 for o in observed if need.issubset(set(o["filters"])))

    cov_path = ROOT / "data" / "coverage.json"
    cov = json.loads(cov_path.read_text()) if cov_path.exists() else {"nights": []}
    cov.setdefault("nights", [])
    cov["nights"] = [n for n in cov["nights"]
                     if not (n.get("date") == date and n.get("telescope", DEFAULT) == scope)]
    cov["nights"].append({
        "date": date, "telescope": scope, "status": "observed",
        "pass": plan.get("pass", 1),
        "mock": True,
        "planned": plan["planned"], "observed": observed,
        "quality": "synthetic",
        "conditions": {"medianFwhmArcsec": round(
            float(np.median([f["fwhm_arcsec"] for f in frames])), 2)},
        "note": f"{MOCK_NOTE} · {len(frames)} frames, {complete} tiles complete",
        "source": str(csv_path.relative_to(ROOT)),
    })
    cov["nights"].sort(key=lambda x: (x["date"], x.get("telescope", "")))
    cov_path.write_text(json.dumps(cov, indent=2))

    print(f"MOCK night {date} [{scope}] pass {plan.get('pass', 1)}")
    print(f"  planned {len(plan['planned'])} -> attempted {len(attempted)} "
          f"({a.completion:.0%}) -> {len(frames)} frames")
    print(f"  {len(observed)} tiles touched, {complete} complete in {'+'.join(sorted(need))}")
    if unmatched:
        print(f"  {unmatched} frames matched no tile within {a.tol}°")
    print(f"  wrote {csv_path.relative_to(ROOT)} and updated data/coverage.json (mock: true)")


if __name__ == "__main__":
    main()
